stages:
  - test

test_py27:
  stage: test
  image: python:2.7
  script:
    - pip -q install tox
    - tox -e py27

test_py35:
  stage: test
  image: python:3.5
  script:
    - pip -q install tox
    - tox -e py35
